apiVersion: v1
kind: Pod
metadata:
 name: busyloop
spec:
 containers:
 - name: busyloop
   image: busybox:1.24
   resources:
    limits:
     cpu: "1000m"
    requests:
     cpu: "1000m"
   command:
   - "/bin/sh"
   - "-c"
   - "while true; do let a=a+1; done"
