apiVersion: v1
kind: Pod
metadata:
  name: ygg-pod
spec:
  restartPolicy: Never
  containers:
  - name: container-1
    image: gcr.io/ygg-gke-dev/gke-tf-tpu:latest
    command: ["sleep"]
    args: ["10000"]
    resources:
      limits:
       alpha.kubernetes.io/nvidia-gpu: 1
    volumeMounts:
    - name: nvidia-debug-tools
      mountPath: /usr/local/bin/nvidia
    - name: nvidia-libraries
      mountPath: /usr/local/nvidia/lib64 # This path is special; it is expected to be present in `/etc/ld.so.conf` inside the container image.
  volumes:
  - name: nvidia-debug-tools # optional
    hostPath:
      path: /home/kubernetes/bin/nvidia/bin
  - name: nvidia-libraries # required
    hostPath:
      path: /home/kubernetes/bin/nvidia/lib
