apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-container
    image: busybox:latest
    command: ["/bin/sleep"]
    args: ["100000"]
    resources:
      requests:
        alpha.google.com/tpu: 2
      limits:
        alpha.google.com/tpu: 2
