apiVersion: admissionregistration.k8s.io/v1alpha1
kind: InitializerConfiguration
metadata:
  name: tpu-initializer
  namespace: default
initializers:
  - name: initializer.tpu.google.com
    rules:
    - apiGroups:
        - ""
      apiVersions:
        - v1
      resources:
        - pods
