apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:tpu-scheduler
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/binding
  - nodes
  - nodes/status
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - initializerconfigurations
  verbs:
  - "*"
- apiGroups:
  - cr.tpu-scheduler.google.com
  resources:
  - tpus
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tpu-scheduler-binding
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:tpu-scheduler
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:tpu-scheduler
